package com.example.calculator;
import android.app.Activity; import android.os.Bundle; import android.graphics.Color; import android.view.Gravity; import android.widget.*; import java.util.Locale;
public class MainActivity extends Activity {
 private TextView display; private String input="0", pending=""; private double stored; private boolean fresh=true;
 public void onCreate(Bundle b){super.onCreate(b); LinearLayout root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(12,24,12,12); root.setBackgroundColor(Color.rgb(18,18,18)); display=new TextView(this); display.setText("0"); display.setTextColor(Color.WHITE); display.setTextSize(42); display.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL); root.addView(display,new LinearLayout.LayoutParams(-1,0,1)); GridLayout grid=new GridLayout(this); grid.setColumnCount(4); String[] keys={"AC","C","⌫","÷","7","8","9","×","4","5","6","−","1","2","3","＋","0",".","="}; for(String k:keys){Button v=new Button(this); v.setText(k); v.setTextSize(22); v.setGravity(Gravity.CENTER); v.setPadding(0,0,0,0); v.setMinHeight(dp(64)); v.setOnClickListener(x->tap(k)); GridLayout.LayoutParams lp=new GridLayout.LayoutParams(); lp.width=0; lp.height=dp(64); lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f); grid.addView(v,lp);} root.addView(grid); setContentView(root); }
 private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
 private void tap(String k){try{if(k.matches("[0-9]")){if(fresh||input.equals("0")){input=k;fresh=false;}else input+=k;}else if(k.equals(".")){if(fresh){input="0";fresh=false;}if(!input.contains("."))input+=".";}else if(k.equals("⌫")){if(input.equals("Error")||input.length()<=1){input="0";}else{input=input.substring(0,input.length()-1);if(input.equals("-0"))input="0";}fresh=false;}else if(k.equals("AC")||k.equals("C")){input="0";pending="";stored=0;fresh=true;}else if(k.equals("=")){if(!pending.isEmpty()){stored=calc(stored,Double.parseDouble(input),pending);input=fmt(stored);pending="";}fresh=true;}else{if(fresh&& !pending.isEmpty()){pending=k.equals("＋")?"+":k.equals("−")?"-":k;}
 else {if(!pending.isEmpty())stored=calc(stored,Double.parseDouble(input),pending);else stored=Double.parseDouble(input);pending=k.equals("＋")?"+":k.equals("−")?"-":k;fresh=true;}}display.setText(input);}catch(Exception e){input="Error";pending="";fresh=true;display.setText(input);}}
 private double calc(double a,double b,String op){if(op.equals("÷")&&b==0)throw new ArithmeticException();return op.equals("+")?a+b:op.equals("-")?a-b:op.equals("×")?a*b:a/b;}
 private String fmt(double n){return String.format(Locale.US,"%.10f",n).replaceAll("0+$","").replaceAll("\\.$","");}
}
